
# CI for NVIP

name: Java CI

on: [push]

env:
  AWS_REGION: 'us-east-1'
  S3_BUCKET_NAME: 'www-staging.cve.live'
  ANGULAR_CLI_VERSION: '15.1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Zip UI
        run: |
          zip -r -q angular-ui.zip angular-ui
      - name: Prepare MySQL DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_backend/nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
      - name: Test and Build backend with Maven
        run: |
          cd nvip_backend
          mvn install:install-file \
            -Dfile=sleepycat-5.0.84.jar \
            -DgroupId=com.sleepycat \
            -DartifactId=je \
            -Dversion=5.0.84 \
            -Dpackaging=jar \
            -DgeneratePom=true
          mvn dependency:go-offline
          mvn package -DskipTests
      - name: Build API with Maven
        run: |
          cd nvip_api
          mvn package -DskipTests
  
  package: 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps: 
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image for backend
        run: |
          cd nvip_backend
          docker build . -t nvip-crawler:dev -t ghcr.io/softwaredesignlab/nvip-crawler:dev
          docker push ghcr.io/softwaredesignlab/nvip-crawler:dev
      - name: Build and Push Docker Image for API
        run: |
          docker build . -t nvip-api:dev -t ghcr.io/softwaredesignlab/nvip-api:dev
          docker push ghcr.io/softwaredesignlab/nvip-api:dev

  build-ui: 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Angular
        uses: actions/setup-node@v2
        uses: actions/checkout@v2
        run: |
          npm install -g @angular/cli@${{ env.ANGULAR_CLI_VERSION }}
          ng build angular-ui

      - name: Deploy to S3
        if: success()
        run: aws s3 sync ./dist/angular-ui s3://${{ env.S3_BUCKET_NAME }}
    