
# CI for NVIP
# author: aep7128
# TODO: Need to resolve sleepycat issue for this to work


name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Zip UI
        run: |
          zip -r -q angular-ui.zip angular-ui
      - name: Prepare MySQL DB
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE nvip;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'source nvip_backend/nvip_data/mysql-database/CreateAndInitializeDb.sql' -uroot -proot
      - name: Test and Build backend with Maven
        run: |
          cd nvip_backend
          
          mvn install:install-file \
            -Dfile=sleepycat-5.0.84.jar \
            -DgroupId=com.sleepycat \
            -DartifactId=je \
            -Dversion=5.0.84 \
            -Dpackaging=jar \
            -DgeneratePom=true
          
          mvn dependency:go-offline
          
          mvn package
          
          docker build . -t nvip-crawler:latest -t ghcr.io/softwaredesignlab/test-nvip-crawler:latest
          
          docker push ghcr.io/softwaredesignlab/test-nvip-crawler:latest
