name: NVIP CI
run-name: Push by ${{ github.actor }}
on: push
jobs:
  Run-NVIP-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Preparing Tests..."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Starting NVIP Backend Tests"
      - name: Compile nvip_backend and run unit tests
      run: |
        cd nvip_backend
        mvn package
      - run: echo "NVIP Backend Tests Finished!"
      - run: echo "Starting NVIP UI Tests"
      - name: Compile nvip_ui and run tests
        run: |
          cd ../nvip_ui
          mvn package
      - run: echo "NVIP Backend Tests Finished!"
      - run: echo "All NVIP Tests Complete!"
      - run: echo "NVIP Tests Status: ${{ job.status }}."